# Generated by Django 3.0 on 2021-09-08 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='اسم التصنيف')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='عن التصنيف')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='اسم الدوره')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='عن الدوره')),
                ('logo', models.ImageField(null=True, upload_to='', verbose_name='لوجو الدوره')),
                ('duration', models.SmallIntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, db_index=True, max_length=128, null=True, unique=True, verbose_name='المسار')),
                ('start_date', models.DateField(null=True, verbose_name='تاريخ البدايه')),
                ('end_date', models.DateField(null=True, verbose_name='تاريخ النهايه')),
                ('total_hours', models.IntegerField(blank=True, null=True, verbose_name='عدد الساعات')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='greenCircle.Category', verbose_name='التصنيف')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Image')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='اسم الملتحق')),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='greenCircle.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenCircle.Trainer', verbose_name='المدرب'),
        ),
    ]
