# Generated by Django 3.0 on 2021-09-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenCircle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequest',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Requests', to='greenCircle.Course'),
        ),
    ]
