# Generated by Django 3.0 on 2021-09-12 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenCircle', '0002_auto_20210912_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='greenCircle.Trainer', verbose_name='المدرب'),
        ),
    ]
