# Generated by Django 3.0 on 2021-09-12 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenCircle', '0003_auto_20210912_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenCircle.Trainer', verbose_name='المدرب'),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='greenCircle.Course'),
        ),
    ]
