# Generated by Django 4.0.1 on 2022-01-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenCircle', '0009_greensurvey_alter_category_id_alter_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greensurvey',
            name='is_accepted',
            field=models.BooleanField(blank=True, choices=[('نعم', True), ('لا', False)], null=True),
        ),
    ]
