# Generated by Django 4.0.1 on 2022-01-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenCircle', '0010_alter_greensurvey_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greensurvey',
            name='is_accepted',
            field=models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], null=True),
        ),
    ]
