# Generated by Django 4.0.1 on 2022-01-16 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenCircle', '0011_alter_greensurvey_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='greensurvey',
            name='document_download',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='green_survey', to='greenCircle.documentdownload'),
        ),
    ]
