# Generated by Django 3.0 on 2022-01-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenCircle', '0013_auto_20220126_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteertrip',
            name='accept_pay',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
