# Generated by Django 3.0 on 2022-01-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenCircle', '0015_volunteertrip_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteertrip',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
