# Generated by Django 3.0 on 2022-01-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenCircle', '0016_volunteertrip_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteertrip',
            name='accept_pay',
            field=models.BooleanField(blank=True, choices=[(True, 'أوافق'), (False, 'لا اوافق')], default=True, null=True),
        ),
    ]
