# Generated by Django 3.0 on 2022-03-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenCircle', '0018_remove_volunteertrip_accept_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greensurvey',
            name='choices',
            field=models.CharField(choices=[('دعم المجتمع النساء ', 'دعم المجتمع النساء '), ('تعليم المكفوفين', 'تعليم المكفوفين'), ('دعم حرفة الخيوط ', 'دعم حرفة الخيوط ')], max_length=255),
        ),
    ]
