# Generated by Django 3.0 on 2022-04-01 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('greenCircle', '0022_messgaes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSurvery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_way', models.TextField(blank=True, null=True)),
                ('provide_help', models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], null=True)),
                ('women_support', models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
