# Generated by Django 3.0 on 2022-04-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenCircle', '0023_topicsurvery'),
    ]

    operations = [
        migrations.AddField(
            model_name='messgaes',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messages/'),
        ),
        migrations.AddField(
            model_name='messgaes',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
