# Generated by Django 3.0 on 2022-04-11 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenCircle', '0024_auto_20220402_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdownload',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='greenCircle.Category'),
        ),
    ]
