# Generated by Django 3.0 on 2022-04-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenCircle', '0026_auto_20220413_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdownload',
            name='choice',
            field=models.CharField(blank=True, choices=[('2_GREEN', 'تكوين دائرة')], max_length=255, null=True),
        ),
    ]
