# Generated by Django 3.0 on 2022-04-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220126_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ممثل المؤسسة'), (2, 'مشرف مركزى'), (3, 'مشرف متطوع'), (4, ' مكون دائرة')], help_text='User Role in A system ', null=True, verbose_name='User Type'),
        ),
    ]
