# Generated by Django 3.0 on 2022-05-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_topicgreen'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicgreen',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
