# Generated by Django 3.0 on 2021-12-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designkhieer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khieerdesign',
            name='image',
            field=models.ImageField(null=True, upload_to='designs/'),
        ),
    ]
