# Generated by Django 3.0 on 2022-02-06 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designkhieer', '0003_auto_20220126_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khieerdesign',
            name='name',
        ),
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('type_clothes', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_order', models.SmallIntegerField(blank=True, max_length=255)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('design_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='designkhieer.KhieerDesign')),
            ],
        ),
    ]
