# Generated by Django 3.0 on 2022-02-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designkhieer', '0004_auto_20220206_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
