# Generated by Django 3.0 on 2022-02-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designkhieer', '0005_designrequest_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
