# Generated by Django 3.0 on 2022-02-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designkhieer', '0006_designrequest_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerJoinUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('national_id', models.IntegerField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('design_filed', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
