# Generated by Django 3.0 on 2022-02-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designkhieer', '0007_designerjoinus'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerjoinus',
            name='is_accept_policy',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
