# Generated by Django 3.0 on 2022-01-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebakhieer', '0002_alter_hebakheer_id_alter_volunteer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hebakheer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
