# Generated by Django 3.0 on 2022-04-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hebakhieer', '0003_auto_20220126_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='cv',
            field=models.FileField(null=True, upload_to='joiners_cv/'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='desc',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='filed',
            field=models.CharField(choices=[('تصميم الجرافيك', 'تصميم الجرافيك'), ('محاسبة مالية', 'محاسبة مالية'), ('تصميم الموشن الجرافيك', 'تصميم الموشن الجرافيك'), ('كتابة المحتوى', 'كتابة المحتوى'), ('التصوير الفوتوغرافى', 'التصوير الفوتوغرافى'), ('التقنية', 'التقنية'), ('الأعمال المكتبية', 'الأعمال المكتبية'), ('التسويق الألكترونى', 'التسويق الألكترونى'), ('تصوير الفيديو ', 'تصوير الفيديو '), ('التدريب', 'التدريب'), ('التنظيم والتنسيق', 'التنظيم والتنسيق'), ('المونتاج تحرير الأفلام', 'المونتاج تحرير الأفلام'), ('التعليق الصوتى', 'التعليق الصوتى'), ('اخرى', 'اخرى')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='place',
            field=models.CharField(choices=[('ميدانى', 'ميدانى'), ('عن بعد', 'عن بعد'), ('الأثنين معا', 'الأثنين معا')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='study',
            field=models.CharField(choices=[('ثانوى', 'ثانوى'), ('متوسط', 'متوسط'), ('جامعى', 'جامعى'), ('دراسات عليا', 'دراسات عليا')], max_length=255, null=True),
        ),
    ]
